import { NextResponse } from 'next/server';

// Simple 192x192 PNG icon as base64
// This is a placeholder - for production, use proper PNG files
const icon192Base64 = 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAIzSURBVHgB7doxAQAgDMCwgX/P0xqKDhBw952ZBVN7AOwywNBkgKHJAEOTAYYmAwxNBhiaDDA0GWBoMsDQZIChyQBDkwGGJgMMTQYYmgwwNBlgaDLA0GSAockAQ5MBhiYDDE0GGJoMMDQZYGgywNBkgKHJAEOTAYYmAwxNBhiaDDA0GWBoMsDQZIChyQBDkwGGJgMMTQYYmgwwNBlgaDLA0GSAockAQ5MBhiYDDE0GGJoMMDQZYGgywNBkgKHJAEOTAYYmAwxNBhiaDDA0GWBoMsDQZIChyQBDkwGGJgMMTQYYmgwwNBlgaDLA0GSAockAQ5MBhiYDDE0GGJoMMDQZYGgywNBkgKHJAEOTAYYmAwxNBhiaDDA0GWBoMsDQZIChyQBDkwGGJgMMTQYYmgwwNBlgaDLA0GSAockAQ5MBhiYDDE0GGJoMMDQZYGgywNBkgKHJAEOTAYYmAwxNBhiaDDA0GWBoMsDQZIChyQBDkwGGJgMMTQYYmgwwNBlgaDLA0GSAockAQ5MBhiYDDE0GGJoMMDQZYGgywNBkgKHJAEOTAYYmAwxNBhiaDDA0GWBoMsDQZIChyQBDkwGGJgMMTQYYmgwwNBlgaDLA0GSAockAQ5MBhiYDDE0GGJoMMDQZYGgywNBkgKHJAEOTAYYmAwxNBhiaDDA0GWBoMsDQZIChyQBDkwGGJgMMTQYYmgwwNBlgaDLA0GSAockAQ5MBhiYDDE0GGJoMMDQZYGgywNBkgKHJAEOTAYb2AGvrAghJkM8jAAAAAElFTkSuQmCC';

export async function GET() {
  const buffer = Buffer.from(icon192Base64, 'base64');

  return new NextResponse(buffer, {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=31536000, immutable',
    },
  });
}
